# This file was generated by GoReleaser. DO NOT EDIT.
cask "codex-bro" do
  name "codex-bro"
  desc "WeChat bridge for talking to Codex and receiving notifications"
  homepage "https://github.com/etng/codex_bro"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codex_bro"

  on_macos do
    on_intel do
      url "https://github.com/etng/codex_bro/releases/download/v#{version}/codex_bro_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/etng/codex_bro/"
      sha256 "8f2ca42e7ad84643c43156970404dd633d40ab6ab67ccc1e6693f27f39ccf1f9"
    end
    on_arm do
      url "https://github.com/etng/codex_bro/releases/download/v#{version}/codex_bro_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/etng/codex_bro/"
      sha256 "006c8e3e66629b79e7e6e5030fc0eff266f7d5807bdaeb135f596e92f0db9adb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/etng/codex_bro/releases/download/v#{version}/codex_bro_#{version}_linux_amd64.tar.gz",
        verified: "github.com/etng/codex_bro/"
      sha256 "6323aabc4fcbc885af9f3115727a14ff91cdeef6139fccae8eb58783ab2aa60d"
    end
    on_arm do
      url "https://github.com/etng/codex_bro/releases/download/v#{version}/codex_bro_#{version}_linux_arm64.tar.gz",
        verified: "github.com/etng/codex_bro/"
      sha256 "1cae1b8e31fac246e91dcbc944c625c61d75ca2555a32780a88cbcfba2aa6f98"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codex_bro"]
    end
  end

  caveats do
    "The installed command is `codex_bro`."
  end

  # No zap stanza required
end
