# This file was generated by GoReleaser. DO NOT EDIT.
cask "codex-bro" do
  name "codex-bro"
  desc "WeChat bridge for talking to Codex and receiving notifications"
  homepage "https://github.com/etng/codex_bro"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codex_bro"

  on_macos do
    on_intel do
      url "https://github.com/etng/codex_bro/releases/download/v#{version}/codex_bro_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/etng/codex_bro/"
      sha256 "2bfc6abaf2e465bd4a26f4da599be2c5c317baaed3a6684ba5f313cba18817c8"
    end
    on_arm do
      url "https://github.com/etng/codex_bro/releases/download/v#{version}/codex_bro_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/etng/codex_bro/"
      sha256 "8362b48e7b495622e8b278532b3fe0764a3bd660c14f610a67fa32fcb89732ec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/etng/codex_bro/releases/download/v#{version}/codex_bro_#{version}_linux_amd64.tar.gz",
        verified: "github.com/etng/codex_bro/"
      sha256 "e79670259f557d313f67cd3a66c90504b5b781a0c347207cbdadd5cba191f39e"
    end
    on_arm do
      url "https://github.com/etng/codex_bro/releases/download/v#{version}/codex_bro_#{version}_linux_arm64.tar.gz",
        verified: "github.com/etng/codex_bro/"
      sha256 "6e8b1cdccc294b32d6ac6da37ac0db45fbfdfdb8b182fbc63aec69bc5833f21e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codex_bro"]
    end
  end

  caveats do
    "The installed command is `codex_bro`."
  end

  # No zap stanza required
end
