# This file was generated by GoReleaser. DO NOT EDIT.
cask "codex-bro" do
  name "codex-bro"
  desc "WeChat bridge for talking to Codex and receiving notifications"
  homepage "https://github.com/etng/codex_bro"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codex_bro"

  on_macos do
    on_intel do
      url "https://github.com/etng/codex_bro/releases/download/v#{version}/codex_bro_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/etng/codex_bro/"
      sha256 "62ee7345f74202671906fa7ea407fe1d0ba999939cd9c9fc6f6e72f8c8b4d62f"
    end
    on_arm do
      url "https://github.com/etng/codex_bro/releases/download/v#{version}/codex_bro_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/etng/codex_bro/"
      sha256 "40043fef33ac31e7cb36f4451e10cf7bac0990baef92dc490187f4a4c8bff52c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/etng/codex_bro/releases/download/v#{version}/codex_bro_#{version}_linux_amd64.tar.gz",
        verified: "github.com/etng/codex_bro/"
      sha256 "e24ce840b8c140521f633f9273b1c8e2542e3012e3021142874184026f566de0"
    end
    on_arm do
      url "https://github.com/etng/codex_bro/releases/download/v#{version}/codex_bro_#{version}_linux_arm64.tar.gz",
        verified: "github.com/etng/codex_bro/"
      sha256 "a2d7ef073181f43bf3d9a9ad9693e08e7329f013287e28fdb0e63fc586a6687c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codex_bro"]
    end
  end

  caveats do
    "The installed command is `codex_bro`."
  end

  # No zap stanza required
end
